### ISSUE TITLE
Implement JWT 

### ISSUE THREAD

**Issue by ngobach26** [ngobach26/CornHub-E-learning-Platform#5]
Referencing these videos: https://www.youtube.com/watch?v=7Q17ubqLfaM , https://www.youtube.com/watch?v=mbsmsi7l3r4&t=303s
After that, implement JWT in our  server.
Then, write a small instruction for others about what you have done, how we can use it ...( the instruction must be clear, short and easy to understand)

**Comment by hieulexuan123** [comment]
Completed
